// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzf-oU0nqQBV5yrhtHhFAyEYAWWl-_60g',
    appId: '1:125087498724:web:38508f0474d54dcf0c87f1',
    messagingSenderId: '125087498724',
    projectId: 'testfcm-5924f',
    authDomain: 'testfcm-5924f.firebaseapp.com',
    databaseURL: 'https://testfcm-5924f.firebaseio.com',
    storageBucket: 'testfcm-5924f.appspot.com',
    measurementId: 'G-5LJDC0YXHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAop1ICzDAUD9XPGy67y-IBwxV75MXdsj0',
    appId: '1:125087498724:android:faa3c85cfa0853630c87f1',
    messagingSenderId: '125087498724',
    projectId: 'testfcm-5924f',
    databaseURL: 'https://testfcm-5924f.firebaseio.com',
    storageBucket: 'testfcm-5924f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAslmkwJG0OAt3XHmsDLWnebg8x-zz1gR0',
    appId: '1:125087498724:ios:0e2fdcde6aa405f80c87f1',
    messagingSenderId: '125087498724',
    projectId: 'testfcm-5924f',
    databaseURL: 'https://testfcm-5924f.firebaseio.com',
    storageBucket: 'testfcm-5924f.appspot.com',
    androidClientId: '125087498724-cmhsci9truk278t3acgf6uv7613sginr.apps.googleusercontent.com',
    iosClientId: '125087498724-fbpeh6iomi65uu0bd50ass2poatuel0g.apps.googleusercontent.com',
    iosBundleId: 'com.shahanul.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAslmkwJG0OAt3XHmsDLWnebg8x-zz1gR0',
    appId: '1:125087498724:ios:0e2fdcde6aa405f80c87f1',
    messagingSenderId: '125087498724',
    projectId: 'testfcm-5924f',
    databaseURL: 'https://testfcm-5924f.firebaseio.com',
    storageBucket: 'testfcm-5924f.appspot.com',
    androidClientId: '125087498724-cmhsci9truk278t3acgf6uv7613sginr.apps.googleusercontent.com',
    iosClientId: '125087498724-fbpeh6iomi65uu0bd50ass2poatuel0g.apps.googleusercontent.com',
    iosBundleId: 'com.shahanul.webrtc',
  );
}
